name: kpi_drive_task
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-290.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter  
  web_socket_channel: ^2.3.0
  freezed: ^2.3.2
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^2.0.0
  build_runner: ^2.4.1


flutter:

  uses-material-design: true

  
